# Generated by Django 6.0.1 on 2026-01-23 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='deposit',
        ),
        migrations.AddField(
            model_name='saving',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='saving_type',
            field=models.CharField(choices=[('compulsory', 'Compulsory'), ('voluntary', 'Voluntary')], default='Voluntary', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saving',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
