# Generated by Django 6.0.1 on 2026-01-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_email_remove_customer_first_name_and_more'),
        ('savings', '0002_remove_saving_deposit_saving_amount_saving_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-date'], 'verbose_name': 'Saving', 'verbose_name_plural': 'Savings'},
        ),
        migrations.AlterField(
            model_name='saving',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
